running:
  covariance: default
  score_threshold: 0.01
  tracker: cp_plus #([immortal,cp_plus])
  max_age_since_update:
    cp_plus: 2
  min_hits_to_birth: 
    immortal: 1
    cp_plus: 1
  match_type: bipartite
  asso: giou
  asso_thres:
    giou: 1.5
    iou: 0.9
    m_dis: 11

data_loader:
  nms: True
  nms_thres: 0.1


# running:
#   covariance: default
#   score_threshold: 0.01
#   max_age_since_update: 2
#   min_hits_to_birth: 1
#   match_type: bipartite
#   asso: giou
#   has_velo: false
#   nms_thres: 0.1
#   motion_model: kf
#   asso_thres:
#     giou: 1.5
#     iou: 0.9
#     m_dis: 11

# redundancy:
#   mode: default
#   det_score_threshold: 
#     iou: 0.01
#     giou: 0.01
#     m_dis: 0.1
#   det_dist_threshold: 
#     iou: 0.1
#     giou: -0.5
#     m_dis: 11

# data_loader:
#   pc: false
  