with_dimensions: True
cost_thresh: 0.1
max_distance: 50
min_overlap: 2
mode: iou3d
box_fuse_func: weighted_box_fuse
keep_unmatch1: True
tracklet_iou: True
box_matched_thresh: 0.8
match: naive
only_moving: True